server:
  port: 9101

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.33.102:13306/seate_order
    username: root
    password: 123456

feign:
  hystrix:
    enabled: false

# Logger Config
logging:
  level:
    com.learn.demo.order.mapper: debug
    io:
      seata: info