server:
  port: 9101

# DataSource Config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver          # mysql驱动包，高版本兼容低版本驱动
    url: jdbc:mysql://192.168.33.102:13306/seate_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: default
    nacos:
      discovery:
        server-addr: localhost:8848

#不建议加框架的逻辑删除
##逻辑删除，使用的是删除方法，实际是更新操作
#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: delete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)com.learn.demo.order.entity.Order.delete字段
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# Logger Config
logging:
  level:
    com.learn.demo.order.mapper: debug