server:
  port: 9102

# DataSource Config
spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver          # mysql驱动包，高版本兼容低版本驱动
#    url: jdbc:mysql://192.168.33.102:13306/seata_storage?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
  application:
    name: seata-storage-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.33.102:13306/seata_storage
     username: root
     password: 123456

feign:
    hystrix:
      enabled: false

  # Logger Config
logging:
    level:
      com.learn.demo.order.mapper: debug
      io:
        seata: info